name = "gbr_ui"
version = "1.0.2-alpha+011"
target = "javascript"

description = "🎨 Gleam UI lustre library by @gleam-br"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gleam-br", repo = "gbr_ui" }
links = []

[dependencies]
gbr_ui_router = { path = "../gbr_ui_router" }
gbr_shared = { path = "../gbr_shared" }
gbr_js = { path = "../gbr_js" }

lustre = "~> 5.5"
rsvp = "~> 1.1"

gleam_time = "~> 1.6"
gleam_http = "~> 4.3"
gleam_json = "~> 3.1"
gleam_stdlib = "~> 0.68"

[dev-dependencies]
gleeunit = "~> 1.0"
