name = "gbr_ui"
version = "1.0.2-alpha+005"

description = "🎨 Gleam UI lustre library by @gleam-br"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gleam-br", repo = "gbr_ui" }
links = []

[dependencies]
lustre = "~> 5.5"
gleam_stdlib = "~> 0.68"

[dev-dependencies]
gleeunit = "~> 1.0"
