name = "gbr_ui_storybook"
version = "1.0.0"
description = "GBR: UI Storybook library"
target = "javascript"
gleam = ">=1.17.0"

repository = { type = "github", user = "gleam-br", repo = "gbr_ui", path = "storybook" }
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 1.0"

lustre = "~> 5.7"

[dev-dependencies]
gleeunit = "~> 1.11"

[javascript]
typescript_declarations = true
