name = "gbr_ui"
version = "1.1.1"
gleam = ">= 1.17.0"

description = "Gleam-BR: UI design system library"
licences = ["Apache-2.0"]

[[links]]
title = "Sponsor"
href = "https://github.com/sponsors/salespaulo"

[repository]
type = "github"
user = "gleam-br"
repo = "gbr_ui"
path = "core"

[dependencies]
gleam_stdlib = "~> 1.0"

lustre = "~> 5.7"

[dev-dependencies]
gleeunit = "~> 1.11"

[javascript]
typescript_declarations = true
