name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.17"

      - name: Test core
        run: | 
          cd core
          gleam deps download
          gleam format
          gleam test
          gleam format --check src test

      - name: Test storybook
        run: | 
          cd storybook
          gleam deps download
          gleam format
          gleam test
          gleam format --check src test

      - name: Test showcase
        run: | 
          cd showcase
          gleam deps download
          gleam format
          gleam test
          gleam format --check src test
